apiVersion: v1
kind: Pod
metadata:
  name: accessingcfg
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      envFrom:
        - configMapRef:
          name: storageclasss
      ports:
        - containerPort: 80
