apiVersion: v1
kind: Pod
metadata:
  name: accessingcfg
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: demo-config
            optional: true
      ports:
        - containerPort: 80
