apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    environment: production
    app: nginx
  annotations:
    com.somehing.idont: "efcwefrg90e5yg46h45h356g34g35g45gb-3"
    jenkins_utl: "https://jenkind.com/catr/applu45"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    env: 
    - name: course
      value: devops
    - name: trainer
      value: siva
    ports:
    - containerPort: 80