apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    cource: "mycource"
  annotations:
    com.somehing.idont: "2k3r9wdc23rf-w4t-g3-5hy-35h-w4tf"
spec:
  containers:
    - name: app
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
    - name: log-aggregator
      image: redis
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
