ARG version
FROM tomcat:${version}
RUN yum install nginx -y 
ARG createuser
RUN adduser ${createuser}
RUN echo "insyalled" >> logs.txt
LABEL version="1.2.32.3"
LABEL url="https://www.fb.com/cource/netedatss"
EXPOSE 80 443
ENV x=10 \
    y=20
COPY logs.txt /home/
ADD https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file /home/details.html

WORKDIR /home
USER ${createuser}
ENTRYPOINT ["nginx", "-g"]
CMD ["daemon off;"]

