pipeline {
    agent {
        node {
            label 'agent1'
        }
    }
    environment{
        hello='this is env vaiable'
    }
    stages {
        stage('1st stage') {
            steps {
                environment{
                    SSH_CREDS = credentials('ssh-auth')
                }
                sh """
                    sudo yum install nginx -y  >> /tmp/leg.txt
                    env| grep hello
                    ${env.hello}
                    echo " ${SSH_CREDS}"
                """
            }
        }
    }
    post {
        fixed { echo 's run failed or was unstable' }
        always { echo ' this is executed the always Pipe' }
    }
}
