pipeline {
    agent {
        node {
            label 'agent1' // Corrected syntax: 'label' instead of '='
        }
    }
    environment{
        demo = "this is demo"
    }
    stages {
        stage('Build') { 
            steps {
                sh """

                echo "thiis is "
                env
                """
            }
        }
        stage('Test') { 
            steps {
                echo "thiis is "
            }
        }
        stage('Deploy') { 
            steps {
                sh """
               echo "thiis is "
               echo "$env.demo"
               """
            }
        }
    }
}