pipeline {
    agent {
        node {
            label 'agent1'
        }
    }
    environment {
        hello = 'this is env vaiable'
    }
    stages {
        stage('1st stage') {
            steps {
                
                sh """
                    sudo yum install nginx -y  >> /tmp/leg.txt
                    env| grep hello
                    ${env.hello}
                   
                """
            }
        }
    }
    post {
        fixed { echo 's run failed or was unstable' }
        always { echo ' this is executed the always Pipe' }
    }
}
